<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.B7QmbN1' shared service.

return $this->privates['.service_locator.B7QmbN1'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.B7QmbN1.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.B7QmbN1": it references class "App\\Entity\\Article" but no such service exists.'],
    'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'session' => ['services', 'session', 'getSessionService.php', true],
]);
