<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.nor5DKm' shared service.

return $this->privates['.service_locator.nor5DKm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tagRepository' => ['privates', 'App\\Repository\\TagRepository', 'getTagRepositoryService.php', true],
]);
