<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.2mqeb5J' shared service.

return $this->privates['.service_locator.2mqeb5J'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'article' => ['privates', '.errored..service_locator.2mqeb5J.App\\Entity\\Article', NULL, 'Cannot autowire service ".service_locator.2mqeb5J": it references class "App\\Entity\\Article" but no such service exists.'],
    'category' => ['privates', '.errored..service_locator.2mqeb5J.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.2mqeb5J": it references class "App\\Entity\\Category" but no such service exists.'],
]);
