<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.LavKRp6' shared service.

return $this->privates['.service_locator.LavKRp6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'articleRepository' => ['privates', 'App\\Repository\\ArticleRepository', 'getArticleRepositoryService.php', true],
    'session' => ['services', 'session', 'getSessionService.php', true],
]);
