<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRiZXfKg\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRiZXfKg/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRiZXfKg.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRiZXfKg\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerRiZXfKg\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'RiZXfKg',
    'container.build_id' => '9403fe95',
    'container.build_time' => 1561362003,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRiZXfKg');
