<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMZSky0x\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMZSky0x/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMZSky0x.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMZSky0x\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMZSky0x\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'MZSky0x',
    'container.build_id' => '1a841f1c',
    'container.build_time' => 1561363636,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerMZSky0x');
