<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKDqPj2H\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKDqPj2H/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKDqPj2H.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKDqPj2H\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKDqPj2H\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KDqPj2H',
    'container.build_id' => '77cb781e',
    'container.build_time' => 1558364763,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKDqPj2H');
